name: CI
on: [push, pull_request]
env:
  go-version: "1.22.x"
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Linux packages
        run: sudo apt install -y --no-install-recommends pandoc gettext

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}

      - name: Run tests
        run: go test -p=1 -coverprofile=coverage.text -covermode=atomic ./...

      - name: Upload coverage
        if: success()
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  release:
    name: Release
    needs: [test]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Linux packages
        run: sudo apt install -y --no-install-recommends pandoc gettext

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}

      - name: Build docs
        run: |
          go install github.com/nyaruka/goflow/cmd/docgen
          docgen
          tar -zcf docs.tar.gz docs

      - name: Publish release
        uses: goreleaser/goreleaser-action@v5
        if: ${{ !contains(github.ref, '-') }}
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
